spring:
    datasource:
        author: sa
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:file:~/test;AUTO_SERVER=TRUE
    h2:
        console:
            enabled: true
            path: /h2
    jackson:
        serialization:
            write_dates_as_timestamps: false
    jpa:
        hibernate:
            ddl-auto: update
keycloak:
    auth-server-url: http://127.0.0.1:8080/auth/
    resource: broken-blog-app
    realm: Brokenblog
    public-client: true
    principal-attribute: preferred_username